on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install libncurses6 (replacement for libtinfo5)
        run: sudo apt-get install -y libncurses6
      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.12 
          buildozer-cmd: buildozer -v android debug
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk
