name: Build Eye Disease Detection App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python 3.12
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    # Step 3: Cache Python dependencies to speed up future builds
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 5: Install system dependencies for Android SDK and Buildozer
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo-dev \
          zlib1g-dev \
          liblzma-dev \
          python3-dev \
          python3-pip \
          unzip \
          curl \
          openjdk-11-jdk

    # Step 6: Set up Android SDK
    - name: Set up Android SDK
      run: |
        curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        sudo mkdir -p /opt/android-sdk/cmdline-tools/latest
        sudo unzip sdk.zip -d /opt/android-sdk/cmdline-tools/latest/

        # Set the ANDROID_SDK_ROOT environment variable
        echo "ANDROID_SDK_ROOT=/opt/android-sdk" | sudo tee -a /etc/environment
        source /etc/environment

        # Accept licenses and install necessary components
        sudo /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        sudo /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"

    # Step 7: Install Buildozer
    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer

    # Step 8: Run Buildozer to build the app
    - name: Build app with Buildozer
      run: |
        buildozer android debug

    # Step 9: Upload APK as an artifact
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: eye_disease_detection_apk
        path: bin/*.apk
