name: Build Eye Disease Detection App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Step 3: Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          zlib1g-dev \
          liblzma-dev \
          python3-dev \
          python3-pip \
          unzip \
          curl \
          openjdk-11-jdk

    # Step 4: Set up Android SDK
    - name: Set up Android SDK
      run: |
        sudo mkdir -p /opt/android-sdk/cmdline-tools/latest
        cd /opt/android-sdk/cmdline-tools/latest
        curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip sdk.zip
        export ANDROID_SDK_ROOT=/opt/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/cmdline-tools/bin:$PATH
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/cmdline-tools/bin/sdkmanager --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"

    # Step 5: Install Buildozer
    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer

    # Step 6: Run Buildozer to build the app
    - name: Build app with Buildozer
      run: |
        buildozer android debug
